### ISSUE TITLE
Campaigns panics when repo has no default branch

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/src-cli#309]
Running over a campaign where defaultBranch is null causes src-cli to panic:

```
➜  src-cli git:(main) ✗ src campaigns preview -n erik -f comby.yml
✅ Parsing campaign spec
✅ Resolving namespace
✅ Preparing container images  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14064b5]

goroutine 180 [running]:
github.com/sourcegraph/src-cli/internal/campaigns.repositoryZipArchivePath(...)
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/run_steps.go:204
github.com/sourcegraph/src-cli/internal/campaigns.fetchRepositoryArchive(0x1637920, 0xc0001009c0, 0x1636860, 0xc0002d5100, 0xc000549180, 0x0, 0x0, 0x0)
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/run_steps.go:176 +0x95
github.com/sourcegraph/src-cli/internal/campaigns.runSteps(0x1637920, 0xc0001009c0, 0x1636860, 0xc0002d5100, 0xc000549180, 0xc0002d5280, 0x1, 0x1, 0xc0000ba100, 0x0, ...)
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/run_steps.go:26 +0x96
github.com/sourcegraph/src-cli/internal/campaigns.(*executor).do(0xc0002f6000, 0x16378e0, 0xc00019c000, 0xc0001148d0, 0x0, 0x0)
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/executor.go:199 +0x37d
github.com/sourcegraph/src-cli/internal/campaigns.(*executor).Start.func1.1(0xc0002f6000, 0x16378e0, 0xc00019c000, 0xc0001148d0)
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/executor.go:97 +0x74
created by github.com/sourcegraph/src-cli/internal/campaigns.(*executor).Start.func1
        /Users/erik/Code/sourcegraph/src-cli/internal/campaigns/executor.go:95 +0xc7
```

**Comment by eseliger** [comment]
Closed in https://github.com/sourcegraph/src-cli/pull/312
