### ISSUE TITLE
panic when running campaigns preview

### ISSUE THREAD

**Issue by evanweible-wf** [sourcegraph/src-cli#404]
CLI version:

```bash
$ src version
Current version: 3.22.4
Recommended Version: 3.22.4
```

Command output:

```
$ src campaigns preview -f campaigns/example/upgrade_package_test/campaign.yaml -cache /tmp/sg
✅ Parsing campaign spec
✅ Resolving namespace
✅ Preparing container images
✅ Resolved repositories
⠏  Executing steps in 1 repositories  
│                                                                                                                                     
└── github.com/Workiva/fluri  pubspec_codemod override test 2.0.0 -f test                                                           9s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x147b5a6]

goroutine 16 [running]:
github.com/sourcegraph/src-cli/internal/campaigns.createChangesetSpec(0xc0000f05a0, 0xc0003a6000, 0xeb, 0xc000010100, 0xeb)
        /home/runner/work/src-cli/src-cli/internal/campaigns/executor.go:327 +0x46
github.com/sourcegraph/src-cli/internal/campaigns.(*executor).do(0xc0003cc000, 0x17702e0, 0xc00009a200, 0xc0000f05a0, 0x0, 0x0)
        /home/runner/work/src-cli/src-cli/internal/campaigns/executor.go:276 +0x545
github.com/sourcegraph/src-cli/internal/campaigns.(*executor).Start.func1.1(0xc0003cc000, 0x17702e0, 0xc00009a200, 0xc0000f05a0)
        /home/runner/work/src-cli/src-cli/internal/campaigns/executor.go:145 +0xa5
created by github.com/sourcegraph/src-cli/internal/campaigns.(*executor).Start.func1
        /home/runner/work/src-cli/src-cli/internal/campaigns/executor.go:138 +0xf6
```

**Comment by evanweible-wf** [comment]
Dug into the stack trace and was able to figure out that the problem was that the campaign spec didn't yet have the `changesetTemplate` defined, but the code in `executor.go` was assuming that some changeset info would be non-null here: https://github.com/sourcegraph/src-cli/blob/3.22.4/internal/campaigns/executor.go#L327

I think this issue should remain open, as the script should handle a null value here without panicking, but I'll open a separate issue asking the question of whether `src campaigns validate` should require `changesetTemplate` and some if its members be defined, because it currently does not.

**Comment by mrnugget** [comment]
Fixed in https://github.com/sourcegraph/src-cli/pull/407

**Comment by mrnugget** [comment]
Thanks for reporting this @evanweible-wf and writing such thorough tickets — it's really appreciated :)

**Comment by evanweible-wf** [comment]
No problem, thank you for the quick fixes!
